Repository TeachMe-CloudUS/teachme-auth-service, pull requests merged in 2024-12, with the labels that each got.

#6 Feature/03 docker
  .github/workflows/docker-deploy.yml
  Dockerfile
Labels: enhancement

#8 Doc/07 openapi
  pom.xml
  src/main/java/us/cloud/teachme/auth_service/config/OpenApiConfig.java
  src/main/java/us/cloud/teachme/auth_service/config/SecurityConfig.java
  src/main/java/us/cloud/teachme/auth_service/controller/AuthController.java
  src/main/java/us/cloud/teachme/auth_service/controller/UserController.java
  src/main/java/us/cloud/teachme/auth_service/model/User.java
  src/main/java/us/cloud/teachme/auth_service/model/UserDto.java
Labels: documentation, enhancement

#10 Fix Dockerfile for Dev Box Repository
  Dockerfile
Labels: Refactor
